### ISSUE TITLE
Why can't I call Typora to open the markdown file using the configuration you provided?

### ISSUE THREAD

**Issue by Jesse3692** [tjx666/open-in-external-app#10]
first ：can't call typora

```json
    "openInExternalApp.openMapper": [
        {
            "extensionName": "md",
            "apps": "D:\\Program Files\\Typora\\bin\\typora.exe"
        }
    ]
```

second: got something wrong，but can call typora

```json
    "openInExternalApp.openMapper": [
        {
            "extensionName": "md",
            "title": "typora",
            "apps": "D:\\Program Files\\Typora\\bin\\typora.exe"
        }
    ]
```
![image](https://user-images.githubusercontent.com/24291671/87870065-36a29e00-c9d7-11ea-89d4-0f1a292addb6.png)

Why does this happen? Not with the right configuration, but with the wrong configuration.

**Comment by tjx666** [comment]
first ：can't call typora

```json
    "openInExternalApp.openMapper": [
        {
            "extensionName": "md",
            "apps": "D:\\Program Files\\Typora\\bin\\typora.exe",
            // !: Because typora is made by electron, you need to set isElectronApp option
            "isElectronApp": true
        }
    ]
```

second: got something wrong，but can call typora

```json
    "openInExternalApp.openMapper": [
        {
            "extensionName": "md",
            // !: title property can only used in apps array
            "title": "typora",
            "apps": "D:\\Program Files\\Typora\\bin\\typora.exe"
        }
    ]
```

**Comment by tjx666** [comment]
What your OS? You need to set your OS using typora to open markdown first. All the applications made by electron have this limitation.

**Comment by Jesse3692** [comment]
> What's your OS? You need to set your OS using typora to open markdown by default first. All the applications made by electron have this limitation.

Sorry, no version information was provided

OS: Windows_NT x64 10.0.19041
![image](https://user-images.githubusercontent.com/24291671/87875626-1f7aa500-ca05-11ea-8c8b-76f9f4163098.png)

I think I have what you've listed, and Typora is the default application to open markdown.

**Comment by tjx666** [comment]
If so, you can remove your conguration, this extension should work.

**Comment by Jesse3692** [comment]
> What's your OS? You need to set your OS using typora to open markdown by default first. All the applications made by electron have this limitation.

I think I found a solution to the problem, using the following configuration instead of the one you mentioned above

```json
"openInExternalApp.openMapper": [
        {
            "extensionName": "md",
            "apps": [
                {
                    "title":"typora",
                    "isElectronApp": true
                }
            ]
        }
    ]
```

**Comment by Jesse3692** [comment]
You can update your documentation to make the configuration parameters clearer

**Comment by tjx666** [comment]
In fact, if your system is Windows and the default app to open `md` file is `typora`, you dont need to config anything, Using configuration only when you want to configure mutiple apps to open `md` file.
