### ISSUE TITLE
The latest version of VS Code has broken this extension

### ISSUE THREAD

**Issue by dlitty** [tjx666/open-in-external-app#18]
After I upgraded to VSCode version 1.57.0, this extension no longer works - choosing a file and issuing the open in external app option does nothing anymore (previously it worked great).   Is there something that needs to be done in regards to their new security features?

**Comment by ihodex** [comment]
For me, it doesn't work with electron apps only

![image](https://user-images.githubusercontent.com/55105210/123538712-dff12880-d73e-11eb-9aa4-e335eb0b67ad.png)

**Comment by HeavenlyChorus** [comment]
![image](https://user-images.githubusercontent.com/13861429/124445424-1cadc700-ddb2-11eb-8011-ea93f4d0028b.png)
same issue here with typora

**Comment by vemonet** [comment]
With Ubuntu 20.04 it was working great to open Markdown with Typora, but now it just open them directly in VisualStudio Code

Any idea to fix this?

**Comment by tjx666** [comment]
I test it in latest insider version 1.61.0, and there is no issus

**Comment by tjx666** [comment]
If this issue still exists, please comment to let me know.
