### ISSUE TITLE
Would you show how could it write for Mac?

### ISSUE THREAD

**Issue by davidperezgar** [tjx666/open-in-external-app#19]
I like this extension. But I'd liked to set up for an App by default.

I write this, but it does not seems to work:
`"openInExternalApp.openMapper": [
		{
		    "extensionName": "pot",
		    "apps": "/Applications/Poedit.app"
		},
		{
		    "extensionName": "po",
		    "openCommand": "/Applications/Poedit.app",
		    "apps": "Poedit"
		}
	  ]`

**Comment by tjx666** [comment]
@davidperezgar Please try:

```json
"openInExternalApp.openMapper": [
    { "extensionName": "pot", "apps": "Poedit" },
    { "extensionName": "po", "apps": "Poedit" }
  ]
```

**Comment by davidperezgar** [comment]
Working! nice! Thanks
