### ISSUE TITLE
`@types/vscode 1.60.0` is not compatible with `engines.vscode ^1.55.0`

### ISSUE THREAD

**Issue by BruceChen2017** [tjx666/open-in-external-app#23]
Currently in package.json, there are `@types/vscode 1.60.0` and `engines.vscode ^1.55.0`. 

When `vsce package`, it throws error:
` ERROR  @types/vscode 1.60.0 greater than engines.vscode ^1.55.0. Consider upgrade engines.vscode or use an older @types/vscode version`

To fix the error, I change `engines.vscode ^1.55.0` to `engines.vscode ^1.60.0`

**Comment by tjx666** [comment]
I will publish new version recently
