### ISSUE TITLE
Does not work from the context menu of a tab with a PDF

### ISSUE THREAD

**Issue by lprc** [tjx666/open-in-external-app#24]
When trying to open a PDF file via context menu of a tab nothing happens. However, when using the context menu of the file browser it works. But opening other files, e.g. txt, does work from tab context menu. I'm on Ubuntu 18.04 with VS Code Version 1.64.2 and the version of this extension I have installed is 0.4.1.

## Doesn't work:
![image](https://user-images.githubusercontent.com/13603403/154654899-ddfe8dce-1744-40e7-847a-f0fad52f1f00.png)

## Works:
![image](https://user-images.githubusercontent.com/13603403/154655375-69988c0a-61ca-4561-9ac3-d59d57ef41ea.png)

**Comment by tjx666** [comment]
open .txt doesn't work maybe that vscode is the default app to open .txt file.
I had disable the menu for webview, because I can't get the file path from a webview.

**Comment by tjx666** [comment]
Try the latest version please!

**Comment by lprc** [comment]
Unfortunately now the context menu entry is totally gone for PDF file when clicking on a tab:

![image](https://user-images.githubusercontent.com/13603403/195789208-c6008fd4-953b-4e8e-9d94-31424655773f.png)

Opening via browser context menu however still works fine. Also other files, like .tex, are working fine with both the browser context menu and the tab context menu.

Still Working:

![image](https://user-images.githubusercontent.com/13603403/195789661-89e8dcbe-0a4f-40e4-9c9e-454e1fef2a4c.png)

extension version: 0.6.3
VS Code version: 1.72.2
on Ubuntu 22.04

If I can provide any logs or whatsoever please let me know. Thank you for still investigating into this!

**Comment by lprc** [comment]
I also tried using the new feature for custom commands, but still the context menu entry doesn't show up for me on tabs.

```
"openInExternalApp.openMapper": [
        {
            "extensionName": "pdf",
            "apps": [
                {
                    "title": "open pdf",
                    "shellCommand": "evince ${file}"
                }
            ]
        }
    ]
```

**Comment by lprc** [comment]
Oh I see. I'm using LaTeX Workshop which displays PDF files using PDF.js internally. After disabling this extension the context menu entry for opening in external app shows up as expected. Thus I guess it is a problem related to LaTeX Workshop instead of this extension. There are also other context menu entries missing which are unrelated to Open in External App so I might open an Issue there (if not already present).
Thank you again!

**Comment by tjx666** [comment]
The menu disappear on webview is by design now:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/41773861/195821477-3666287c-2050-4d89-8c1f-a2c9b5b92d84.png">

Because I can get the relative file path of a webview.
