### ISSUE TITLE
Run shell script as "External App" on Mac

### ISSUE THREAD

**Issue by martin-guddat** [tjx666/open-in-external-app#28]
The configuration mentions entering a shell command as openCommand
` // openCommand can be shell command or the complete executable application path`

I would expect something like
` "openCommand": "/System/User/bin/shellscript.sh"`
(or some kind of launching app with the name of the script as `arg`).

I can find no way to get a shell script to run as external command. I tried several ways but without success.
The script should get the file name as parameter. Is there a way to do to this (running macOS).
If this is possible an example would be greatly appreciated!

**Comment by tjx666** [comment]
For running a file, I recommend using https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner
