### ISSUE TITLE
Support passing command line arguments

### ISSUE THREAD

**Issue by kanlukasz** [tjx666/open-in-external-app#3]
Hello

It would be useful to have support for support passing command line arguments
Applications have various cmd arguments that can be useful, such as private mode in web browsers

Example:
```
{
  "title": "firefox",
  "openCommand": "C:\\Program Files\\Firefox Developer Edition\\firefox.exe -private-window"
}
```

**Comment by tjx666** [comment]
Ok, I will try to implement it these days.

**Comment by tjx666** [comment]
I have published the new version to support it~

**Comment by tjx666** [comment]
I have published the new version to support it~

**Comment by kanlukasz** [comment]
Works great. Thank you so much
