### ISSUE TITLE
Missing Translations?

### ISSUE THREAD

**Issue by fnfontana** [tjx666/open-in-external-app#37]
Hello,
I'm using VS Code in PT-BR (Brazilian Portuguese) and the layout texts from this extension are showing only in English. If there's already a translation to Portuguese, I'm unable to see it here. Elsewhere, I can offer myself to translate to my language on the next weekend.

**Comment by tjx666** [comment]
PR welcome, you can ref: https://github.com/Gruntfuggly/todo-tree/commit/9282fb2e555e2a7f1745dbd552fcc038f8a2c223#diff-9b29d8b47a74097a04da353b72a8632d485d658282457b97b4caf26575a42dd0

**Comment by tjx666** [comment]
@fnfontana You can help to translate extension by translate following json string value:

```
{
    "cmd.open": "Open in External App",
    "cmd.openMultiple": "Open in Multiple External Apps",

    "msg.error.configFormat": "Your extension configuration format isn't correct!",
    "msg.error.sameTitleMultipleApp": "Not allowed to set two applications using the same title, please correct your configuration first!",
    "msg.quickPick.selectApp.placeholder": "Select application to open the file...",
    "msg.quickPick.selectApps.placeholder": "Select multiple applications to open the file...",

    "cfg.openInExternalApp.openMapper": "Mapper between the file extensionName and application to open it",
    "cfg.openInExternalApp.openMapper.item.extensionName.string": "File extension name，for example: md",
    "cfg.openInExternalApp.openMapper.item.extensionName.array": "Pass string array to match multiple extension names",
    "cfg.openInExternalApp.openMapper.item.apps": "External applications to open the file",
    "cfg.openInExternalApp.openMapper.item.apps.string": "Command you can access from shell or absolute path of executable program",
    "cfg.openInExternalApp.openMapper.item.apps.array": "External applications info",
    "cfg.openInExternalApp.openMapper.item.apps.item.title": "Title which will be shown in the drop list if there are several apps to open the file",
    "cfg.openInExternalApp.openMapper.item.apps.item.shellCommand": "Using shell command with file placeholder to deal with file",
    "cfg.openInExternalApp.openMapper.item.apps.item.args": "Arguments passed to openCommand",
    "cfg.openInExternalApp.openMapper.item.apps.item.isElectronApp": "Set to true when you config an electron app"
}

```

**Comment by fnfontana** [comment]
> @fnfontana You can help to translate extension by translate following json string value:
> 
> ```
> {
>     "cmd.open": "Open in External App",
>     "cmd.openMultiple": "Open in Multiple External Apps",
> 
>     "msg.error.configFormat": "Your extension configuration format isn't correct!",
>     "msg.error.sameTitleMultipleApp": "Not allowed to set two applications using the same title, please correct your configuration first!",
>     "msg.quickPick.selectApp.placeholder": "Select application to open the file...",
>     "msg.quickPick.selectApps.placeholder": "Select multiple applications to open the file...",
> 
>     "cfg.openInExternalApp.openMapper": "Mapper between the file extensionName and application to open it",
>     "cfg.openInExternalApp.openMapper.item.extensionName.string": "File extension name，for example: md",
>     "cfg.openInExternalApp.openMapper.item.extensionName.array": "Pass string array to match multiple extension names",
>     "cfg.openInExternalApp.openMapper.item.apps": "External applications to open the file",
>     "cfg.openInExternalApp.openMapper.item.apps.string": "Command you can access from shell or absolute path of executable program",
>     "cfg.openInExternalApp.openMapper.item.apps.array": "External applications info",
>     "cfg.openInExternalApp.openMapper.item.apps.item.title": "Title which will be shown in the drop list if there are several apps to open the file",
>     "cfg.openInExternalApp.openMapper.item.apps.item.shellCommand": "Using shell command with file placeholder to deal with file",
>     "cfg.openInExternalApp.openMapper.item.apps.item.args": "Arguments passed to openCommand",
>     "cfg.openInExternalApp.openMapper.item.apps.item.isElectronApp": "Set to true when you config an electron app"
> }
> 
> ```

Thanks for waiting, I was very busy on the last days. I've send the PR.

**Comment by tjx666** [comment]
Thanks your work.
