### ISSUE TITLE
Open .vnc connections

### ISSUE THREAD

**Issue by joellutz** [tjx666/open-in-external-app#38]
I want to be able to open VNC connections with the UltraVNC viewer from a .vnc connection settings file, but I can't seem to get this working.

Opening the connection via the command line works fine just like this:
`start "C:/Program Files/UltraVNC/vncviewer.exe" someConnection.vnc`

Also clicking on the `someConnection.vnc` file from within the file explorer opens the connection.

But when trying this with this VS code extension, it won't open anything. Nothing happens if I click "Open in External App" on the `someConnection.vnc` file from within VS code.

My settings:
```
"openInExternalApp.openMapper": [
        {
            "extensionName": "vnc",
            "apps": "C:/Program Files/UltraVNC/vncviewer.exe"
        }
    ]
```

Is there something wrong with my configuration?

**Comment by joellutz** [comment]
Thanks for the quick response.

1. With `"isElectronApp": true` i get the error message 

> "[0].isElectronApp" is not allowed
> Your configuration format isn't correct

2. With or without `"isElectronApp": true`, I don't get any logs in any console.

**Comment by tjx666** [comment]
Can you provide a screen recording of you operation steps?

**Comment by joellutz** [comment]
1. .vnc is not a binary type. It contains the connection information like IP, Port and other settings for the [UltraVNC Viewer](https://uvnc.com/) in text form, which allows to remote control a pc. I've tried it with the latest version, but it didn't open either.
2. Here is a recording: As you can see, you can't see anything (no VNC-Window or anything has been opened, no logs can be seen).

https://user-images.githubusercontent.com/38663151/195261988-86c6bb48-65fe-42ea-8e3e-a575c8383510.mp4

**Comment by tjx666** [comment]
try config extension like:

```
{
            "extensionName": "vnc",
            "apps": [
                {
                    "title": "vncviewer connect"
                    "shellCommand": "start \"C:/Program Files/UltraVNC/vncviewer.exe\" ${file}"
                }
            ]
}
```

**Comment by joellutz** [comment]
Yes, now it works perfectly! Thank you very much!
