### ISSUE TITLE
Open Typora failed, 2022

### ISSUE THREAD

**Issue by FengZhiheng** [tjx666/open-in-external-app#46]
### Description

I can not open my md files with this plugin. 

### Extension Version

0.8.4

### VS Code Version

![image](https://user-images.githubusercontent.com/27288257/201372021-d682149d-8eaa-4a16-91ba-2df0f3a92268.png)

### Extension Settings

  "openInExternalApp.openMapper": [
    {
      "extensionName": "md",
      "apps": [
        {
          "isElectronApp": true,
          "title": "typora",
          "openCommand": "C:/Program Files/Typora/Typora.exe"
        }
      ]
    },
  ],

### Logs, Screenshots, Screen Recording etc

parsed extension name: md
matchedConfigItem:
{
    "extensionName": "md",
    "apps": [
        {
            "isElectronApp": true,
            "title": "typora",
            "openCommand": "C:/Program Files/Typora/Typora.exe"
        }
    ]
}
Opened file is: "c:\Users\XXX\Documents\GitHub\X\source\about\index.md"
Open file by vscode builtin api

**Comment by tjx666** [comment]
If you want to open `md` file by typora, you need to set typora as windows default app to open `md` file.

**Comment by FengZhiheng** [comment]
> If you want to open `md` file by typora, you need to set typora as windows default app to open `md` file.

I have already set typora as default app to open `md` files. But it is still not work for me. 

![image](https://user-images.githubusercontent.com/27288257/201508348-47ef1b08-e048-4326-8ea3-4ca8e48f4dcb.png)


The output as follow:

```
parsed extension name: md
matchedConfigItem:
{
    "extensionName": "md",
    "apps": [
        {
            "isElectronApp": true,
            "title": "typora",
            "openCommand": "C:\\Program Files\\Typora\\Typora.exe"
        }
    ]
}
Opened file is: "c:\Users\XXX\Documents\GitHub\ZhihengBlog\source\_drafts\小结.md"
Open file by vscode builtin api
```

My system is win11. Thank you very much~

**Comment by jamesfancy** [comment]
It's cannot work in current version

- VSCode v1.73.1
- Open in External App v0.8.4
- Typora v1.2.5
- Windows 11 v10.0.22000 N/A Build 22000

But it works in older version. I am not sure to know the version since I haven't use it in several monthes.

---

Typora is already set as default application for `.md` files so I can open it by double click in windows explorer.

Here is my settings:

```json
    "openInExternalApp.openMapper": [
        {
            "apps": [
                {
                    "isElectronApp": true,
                    "title": "typora"
                }
            ],
            "extensionName": "md"
        }
    ],
```

**Comment by tjx666** [comment]
@FengZhiheng @jamesfancy  VSCode On windows doesn't support to open file which file name includes none-ascill-character

For validate, you can rename your file name to readme.md, ant try to open again

**Comment by FengZhiheng** [comment]
> @FengZhiheng @jamesfancy VSCode On windows doesn't support to open file which file name includes none-ascill-character
> 
> For validate, you can rename your file name to readme.md, ant try to open again

It is still not work for me. The log information as following:
```
parsed extension name: md
matchedConfigItem:
{
    "extensionName": "md",
    "apps": [
        {
            "isElectronApp": true,
            "title": "typora",
            "openCommand": "C:\\Program Files\\Typora\\Typora.exe"
        }
    ]
}
Opened file is: "c:\Users\FengZhiheng\Documents\GitHub\ZhihengBlog\source\_drafts\testConclusion.md"
Open file by vscode builtin api
```
Nothing happened.

**Comment by jamesfancy** [comment]
> @FengZhiheng @jamesfancy VSCode On windows doesn't support to open file which file name includes none-ascill-character
> 
> For validate, you can rename your file name to readme.md, ant try to open again

In my case, all characters in path and filename are ASCII (refer to the picture below). It cannot work yet.

![image](https://user-images.githubusercontent.com/3953094/209268123-1999e408-e312-4c49-b655-30c4d435d6f4.png)

---

VSCode udpate to **1.74.2** now, Open in External App **v0.9.0**

Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

---

The log:

```
open with configItem:
{
    "apps": [
        {
            "isElectronApp": true,
            "title": "typora"
        }
    ],
    "extensionName": "md"
}
opened file is: "d:\James\Workspace\viyi-strings\README.md"
open file by vscode builtin api
```

I tried use `start README.md` in powershell. It worked well. The file was opened by Typora.

**Comment by tjx666** [comment]
@jamesfancy try latest version

**Comment by FengZhiheng** [comment]
> @jamesfancy @FengZhiheng please try latest version

Excellent job! It works now, thank your very much!

**Comment by jamesfancy** [comment]
> @jamesfancy @FengZhiheng please try latest version

It works. Excellent! Thank you!
