### ISSUE TITLE
No longer working in WSL

### ISSUE THREAD

**Issue by King-of-Infinite-Space** [tjx666/open-in-external-app#58]
### Description

commit 9a7234c changed `wslToWindowsSync` to `windowsToWsl` which should be `wslToWindows`

reverting to version before this commit works

#53 should be due to this since it is in WSL

### Extension Version

0.9.10

### VS Code Version

Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.23506

### Extension Settings

none

### Logs, Notifications, Screenshots, Screen Recording etc

none

**Comment by tjx666** [comment]
please try latest version

**Comment by King-of-Infinite-Space** [comment]
Thanks for inviting, I pushed a commit to fix this
The goal is to convert the file path from Linux style to Windows style so that programs in Windows can open it, hence it's `wslToWindows`

**Comment by King-of-Infinite-Space** [comment]
fixed in 0.10.0
