### ISSUE TITLE
Files with a long dash cannot be opened

### ISSUE THREAD

**Issue by kanlukasz** [tjx666/open-in-external-app#6]
Long dash file name example: `Untitled—2.php`

I discovered it by accident
I don't know what the situation is like with other special characters

#### Example:
![obraz](https://user-images.githubusercontent.com/30685349/83552260-c1a00580-a509-11ea-97df-b7081930acd8.png)

#### My environment:
```
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by tjx666** [comment]
What's your default application to open php file?

**Comment by kanlukasz** [comment]
Notepad++

If I try to open a file without this special character in name, it works fine

![obraz](https://user-images.githubusercontent.com/30685349/83642722-7fc99a80-a5af-11ea-9f4f-ab31b5665a95.png)

**Comment by tjx666** [comment]
I will try to fix this problem these days. This problem is caused by the API `vscode.env.openExternal`   doesn't support non-ascii characters in file path.

**Comment by tjx666** [comment]
try the new version V0.1.0

**Comment by kanlukasz** [comment]
Works great, thank you so much !
