### ISSUE TITLE
关于配置Typora打开md文件

### ISSUE THREAD

**Issue by yaronzz** [tjx666/open-in-external-app#7]
```
"openInExternalApp.openMapper": [
        {
            "extensionName": "md",
            "apps": [
                {
                    "title": "Typora",
                    "openCommand": "E:\\Typora\\Typora.exe",
                    "args": ["${file}"]
                }
            ]
        },
    ],
```
你好，我配置文件中加上了以上配置，但右键菜单点击Open in external app之后却没有反应，请问是哪里配置错了吗？

**Comment by kanlukasz** [comment]
1. Did you tried without `"args": ["${file}"]` ?
2. What does the file name you are trying to open look like? I ask because https://github.com/tjx666/open-in-external-app/issues/5 and https://github.com/tjx666/open-in-external-app/issues/6

_By the way - as Github is a global community, it is recommended to use English in issues. As a result, many people around the world can try to help solve problems 😉_

**Comment by yaronzz** [comment]
Remove `"args": ["${file}"]` , still not working.
File name: `readme.md`

**Comment by kanlukasz** [comment]
1. Do you have any error or warning in `Toggle Developer Tools`?
2. Which version of `VSCode` do you use?
4. Which version of the `open-in-external-app ` do you use?
4. Have you tried to reproduce this problem with other extensions turned off? _(The portable VSCode version is useful for this if you do not want to touch your current instance)_

**Comment by yaronzz** [comment]
1. No err-message. what is Toggle Developer Tools?
2. VSCode version '1.45.1(user setup)'
3. Open in external app version '0.0.8'
4. Turned off other extensions, still not working

**Comment by kanlukasz** [comment]
It's right there:
 ![obraz](https://user-images.githubusercontent.com/30685349/83747089-67fe1f00-a660-11ea-8007-4d27a1c55b81.png)

If you have there any error or warning regarding this plugin, you can copy it here. This is sometimes helpful to identify the problem

Thank you for completing the entire report.
You must wait for verification from @tjx666

**Comment by tjx666** [comment]
1. For now, this extension doesn't support argument in settings, so `"args": ["${file}"]` is useless.
2. If you want to open file in application which is made by electron, for example: typora, you can only choose two ways:

```javascript
// 1. don not config it in VSCode settings, and set typora as the default application of your operation system to open `.md` file.

// 2. using isElectronApp option, the `openCommand` and `args` config item is not work. 
{
    "title": "typora",
    "extensionName": "md",
    "isElectronApp": "/path/to/typora.exe"
}
```

---
首先，目前不支持在配置中使用参数。
有两种解决办法：
如果你想在使用 electron 开发的应用例如 typora 中打开 markdown 文件，你有两种方式：
1. 你可以直接不配置 VSCode，但是你要设置 typora 为你操作系统默认的打开 markdown 文件的应用。
2. 或者配置的时候使用使用 `isElectronApp` 选项，使用 `isElectron` 选项的话 `openCommand` 和 `args` 配置项就没有用了。

@yaronzz

**Comment by yaronzz** [comment]
Thanks, add 'isElectronApp' and it works now. @kanlukasz @tjx666 
```
"openInExternalApp.openMapper": [
        {
            "extensionName": "md",
            "apps": [
                {
                    "isElectronApp": true,
                    "title": "Typora",
                    "openCommand": "E:\\Typora\\Typora.exe"
                }
            ]
        },
    ],
```
