### ISSUE TITLE
Please add shortcut

### ISSUE THREAD

**Issue by ChirsGod** [tjx666/open-in-external-app#8]
Please add a shortcut key to call the plug-in command, you can quickly open the corresponding program through the shortcut key.
![图片标题](https://i.loli.net/2018/08/12/5b6fb8f378e8b.jpg)

**Comment by tjx666** [comment]
![screenshot_2020-07-11_18-47-50](https://user-images.githubusercontent.com/41773861/87222557-0ccdf380-c3a7-11ea-95ff-e4076092acb9.png)

You can custom shoutcut of any command you can find in command panel
